services:
  postgres-db:
    image: postgres
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: medicine
      PG_DATA: /var/lib/postgresql/data 
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - eco

  migrate:
    image: migrate/migrate
    networks:
      - eco
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://postgres:1111@postgres:5432/medicine?sslmode=disable", "up"]
    depends_on:
      - postgres-db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - eco

  user-service:
    build: .
    container_name: user-service
    ports:
      - "7777:7777"
    depends_on:
      - postgres-db
      - redis
    networks:
      - eco

volumes:
  postgres-data:
  redis-data:

networks:
  eco:
    driver: bridge
