// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.12.4
// source: rating.proto

package rating

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Rating_CreateUserRating_FullMethodName = "/Rating/CreateUserRating"
	Rating_GetUserActivity_FullMethodName  = "/Rating/GetUserActivity"
	Rating_GetUserRating_FullMethodName    = "/Rating/GetUserRating"
)

// RatingClient is the client API for Rating service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RatingClient interface {
	CreateUserRating(ctx context.Context, in *RatingReq, opts ...grpc.CallOption) (*RatingResp, error)
	GetUserActivity(ctx context.Context, in *FilterActivity, opts ...grpc.CallOption) (*Activity, error)
	GetUserRating(ctx context.Context, in *FilterField, opts ...grpc.CallOption) (*UserRating, error)
}

type ratingClient struct {
	cc grpc.ClientConnInterface
}

func NewRatingClient(cc grpc.ClientConnInterface) RatingClient {
	return &ratingClient{cc}
}

func (c *ratingClient) CreateUserRating(ctx context.Context, in *RatingReq, opts ...grpc.CallOption) (*RatingResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RatingResp)
	err := c.cc.Invoke(ctx, Rating_CreateUserRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratingClient) GetUserActivity(ctx context.Context, in *FilterActivity, opts ...grpc.CallOption) (*Activity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Activity)
	err := c.cc.Invoke(ctx, Rating_GetUserActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratingClient) GetUserRating(ctx context.Context, in *FilterField, opts ...grpc.CallOption) (*UserRating, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserRating)
	err := c.cc.Invoke(ctx, Rating_GetUserRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RatingServer is the server API for Rating service.
// All implementations must embed UnimplementedRatingServer
// for forward compatibility
type RatingServer interface {
	CreateUserRating(context.Context, *RatingReq) (*RatingResp, error)
	GetUserActivity(context.Context, *FilterActivity) (*Activity, error)
	GetUserRating(context.Context, *FilterField) (*UserRating, error)
	mustEmbedUnimplementedRatingServer()
}

// UnimplementedRatingServer must be embedded to have forward compatible implementations.
type UnimplementedRatingServer struct {
}

func (UnimplementedRatingServer) CreateUserRating(context.Context, *RatingReq) (*RatingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserRating not implemented")
}
func (UnimplementedRatingServer) GetUserActivity(context.Context, *FilterActivity) (*Activity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserActivity not implemented")
}
func (UnimplementedRatingServer) GetUserRating(context.Context, *FilterField) (*UserRating, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserRating not implemented")
}
func (UnimplementedRatingServer) mustEmbedUnimplementedRatingServer() {}

// UnsafeRatingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RatingServer will
// result in compilation errors.
type UnsafeRatingServer interface {
	mustEmbedUnimplementedRatingServer()
}

func RegisterRatingServer(s grpc.ServiceRegistrar, srv RatingServer) {
	s.RegisterService(&Rating_ServiceDesc, srv)
}

func _Rating_CreateUserRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RatingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServer).CreateUserRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rating_CreateUserRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServer).CreateUserRating(ctx, req.(*RatingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rating_GetUserActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterActivity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServer).GetUserActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rating_GetUserActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServer).GetUserActivity(ctx, req.(*FilterActivity))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rating_GetUserRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterField)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServer).GetUserRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rating_GetUserRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServer).GetUserRating(ctx, req.(*FilterField))
	}
	return interceptor(ctx, in, info, handler)
}

// Rating_ServiceDesc is the grpc.ServiceDesc for Rating service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rating_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Rating",
	HandlerType: (*RatingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUserRating",
			Handler:    _Rating_CreateUserRating_Handler,
		},
		{
			MethodName: "GetUserActivity",
			Handler:    _Rating_GetUserActivity_Handler,
		},
		{
			MethodName: "GetUserRating",
			Handler:    _Rating_GetUserRating_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rating.proto",
}
